=== aws-greengrass/aws-greengrass-gdk-cli/gdk/static/user_input_recipe_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "RecipeFormatVersion": {
            "type": "string",
            "enum": ["2020-01-25"]
        },
        "ComponentName": {
            "type": "string",
            "oneOf": [
                {"pattern": "^[a-zA-Z0-9-_.]+$"},
                {"enum": ["{COMPONENT_NAME}"]}
            ],
            "maxLength": 128
        },
        "ComponentVersion": {
            "type": "string",
            "maxLength": 64,
            "oneOf": [
                {
                    "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?"
                },
                {
                    "enum": ["NEXT_PATCH", "{COMPONENT_VERSION}"]
                }
            ]
        },
        "ComponentDescription": {
            "type": "string"
        },
        "ComponentPublisher": {
            "type": "string"
        },
        "ComponentConfiguration": {
            "type": "object",
            "properties": {
                "DefaultConfiguration": {}
            }
        },
        "ComponentDependencies": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "VersionRequirement": {
                        "type": "string"
                    },
                    "DependencyType": {
                        "type": "string",
                        "enum": ["SOFT", "HARD"]
                    }
                }
            }
        },
        "ComponentType": {
            "type": "string"
        },
        "ComponentSource": {
            "type": "string",
            "pattern": "^arn:aws:lambda:.*$"
        },
        "Manifests": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "Name": {
                        "type": "string"
                    },
                    "Platform": {
                        "type": "object",
                        "properties": {
                            "os": {
                                "type": "string"
                            },
                            "architecture": {
                                "type": "string"
                            },
                            "architecture.detail": {
                                "type": "string"
                            },
                            "key": {
                                "type": "string"
                            }
                        },
                        "additionalProperties": false
                    },
                    "Lifecycle": {
                        "type": "object",
                        "properties": {
                            "Setenv": {
                                "type": "object",
                                "additionalProperties": {
                                    "type": "string"
                                }
                            },
                            "install": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "Script": {
                                                "type": "string"
                                            },
                                            "RequiresPrivilege": {
                                                "type": "boolean"
                                            },
                                            "Skipif": {
                                                "type": "string"
                                            },
                                            "Timeout": {
                                                "type": "integer",
                                                "minimum": 0
                                            },
                                            "Setenv": {
                                                "type": "object",
                                                "additionalProperties": {
                                                    "type": "string"
                                                }
                                            }
                                        },
                                        "additionalProperties": false
                                    }
                                ]
                            },
                            "run": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "Script": {
                                                "type": "string"
                                            },
                                            "RequiresPrivilege": {
                                                "type": "boolean"
                                            },
                                            "Skipif": {
                                                "type": "string"
                                            },
                                            "Timeout": {
                                                "type": "integer",
                                                "minimum": 0
                                            },
                                            "Setenv": {
                                                "type": "object",
                                                "additionalProperties": {
                                                    "type": "string"
                                                }
                                            }
                                        },
                                        "additionalProperties": false
                                    }
                                ]
                            },
                            "startup": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "Script": {
                                                "type": "string"
                                            },
                                            "RequiresPrivilege": {
                                                "type": "boolean"
                                            },
                                            "Skipif": {
                                                "type": "string"
                                            },
                                            "Timeout": {
                                                "type": "integer",
                                                "minimum": 0
                                            },
                                            "Setenv": {
                                                "type": "object",
                                                "additionalProperties": {
                                                    "type": "string"
                                                }
                                            }
                                        },
                                        "additionalProperties": false
                                    }
                                ]
                            },
                            "shutdown": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "Script": {
                                                "type": "string"
                                            },
                                            "RequiresPrivilege": {
                                                "type": "boolean"
                                            },
                                            "Skipif": {
                                                "type": "string"
                                            },
                                            "Timeout": {
                                                "type": "integer",
                                                "minimum": 0
                                            },
                                            "Setenv": {
                                                "type": "object",
                                                "additionalProperties": {
                                                    "type": "string"
                                                }
                                            }
                                        },
                                        "additionalProperties": false
                                    }
                                ]
                            },
                            "recover": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "Script": {
                                                "type": "string"
                                            },
                                            "RequiresPrivilege": {
                                                "type": "boolean"
                                            },
                                            "Skipif": {
                                                "type": "string"
                                            },
                                            "Timeout": {
                                                "type": "integer",
                                                "minimum": 0
                                            },
                                            "Setenv": {
                                                "type": "object",
                                                "additionalProperties": {
                                                    "type": "string"
                                                }
                                            }
                                        },
                                        "additionalProperties": false
                                    }
                                ]
                            },
                            "bootstrap": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "Script": {
                                                "type": "string"
                                            },
                                            "RequiresPrivilege": {
                                                "type": "boolean"
                                            },
                                            "Timeout": {
                                                "type": "integer",
                                                "minimum": 0
                                            },
                                            "Setenv": {
                                                "type": "object",
                                                "additionalProperties": {
                                                    "type": "string"
                                                }
                                            }
                                        },
                                        "additionalProperties": false
                                    }
                                ]
                            }
                        },
                        "additionalProperties": false
                    },
                    "Selections": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "Artifacts": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "URI": {
                                    "type": "string"
                                },
                                "Unarchive": {
                                    "type": "string",
                                    "enum": [
                                        "NONE",
                                        "ZIP"
                                    ]
                                },
                                "Permission": {
                                    "type": "object",
                                    "properties": {
                                        "Read": {
                                            "type": "string",
                                            "enum": [
                                                "NONE",
                                                "OWNER",
                                                "ALL"
                                            ]
                                        },
                                        "Execute": {
                                            "type": "string",
                                            "enum": [
                                                "NONE",
                                                "OWNER",
                                                "ALL"
                                            ]
                                        }
                                    },
                                    "additionalProperties": false
                                },
                                "Digest": {
                                    "type": "string"
                                },
                                "Algorithm": {
                                    "type": "string"
                                }
                            },
                            "additionalProperties": false
                        }
                    }
                },
                "additionalProperties": false
            }
        },
        "Lifecycle": {
            "type": "object"
        }
    },
    "required": ["RecipeFormatVersion", "ComponentName"],
    "additionalProperties": false
}

=== aws-greengrass/aws-greengrass-gdk-cli/tests/gdk/static/sample_recipes/recipe_gg_client_device_auth.json
{
  "RecipeFormatVersion": "2020-01-25",
  "ComponentName": "{COMPONENT_NAME}",
  "ComponentVersion": "{COMPONENT_VERSION}",
  "ComponentType": "aws.greengrass.plugin",
  "ComponentDescription": "The client device auth component authenticates client devices and authorizes client device actions, so client devices can connect to your Greengrass core device. This component creates the certificate vended by the local MQTT broker.",
  "ComponentPublisher": "{COMPONENT_PUBLISHER}",
  "ComponentDependencies": {
    "aws.greengrass.Nucleus": {
      "VersionRequirement": ">=2.2.0 <2.10.0",
      "DependencyType": "SOFT"
    }
  },
  "Manifests": [
    {
      "Platform": {
        "os": "*"
      },
      "Lifecycle": {},
      "Artifacts": [
        {
          "URI": "s3://aws.greengrass.clientdevices.Auth.jar"
        }
      ]
    }
  ]
}

=== aws-greengrass/aws-greengrass-gdk-cli/tests/gdk/static/sample_recipes/recipe_gg_disk_spooler.json
{
  "RecipeFormatVersion": "2020-01-25",
  "ComponentName": "{COMPONENT_NAME}",
  "ComponentVersion": "{COMPONENT_VERSION}",
  "ComponentType": "aws.greengrass.plugin",
  "ComponentDescription": "The Disk Spooler component stores MQTT messages destined for AWS IoT Core in a database, as opposed to in memory, when offline.",
  "ComponentPublisher": "{COMPONENT_PUBLISHER}",
  "ComponentDependencies": {
    "aws.greengrass.Nucleus": {
      "VersionRequirement": ">=2.2.0 <2.11.0",
      "DependencyType": "SOFT"
    }
  },
  "Manifests": [
    {
      "Platform": {
        "os": "*"
      },
      "Lifecycle": {},
      "Artifacts": [
        {
          "URI": "s3://aws.greengrass.DiskSpooler.jar"
        }
      ]
    }
  ]
}
